apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner-namespace-role
  namespace: arc-runners
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-namespace-binding
  namespace: arc-runners
subjects:
  - kind: ServiceAccount
    name: mi-runners-gha-rs-no-permission
    namespace: arc-runners
roleRef:
  kind: Role
  name: arc-runner-namespace-role
  apiGroup: rbac.authorization.k8s.io

